
---
- name: Remove all the Java related packages
  shell: dpkg-query -W -f='${binary:Package}\n' | grep -E -e '^(ia32-)?(sun|oracle)-java' -e '^openjdk-' -e '^icedtea' -e '^(default|gcj)-j(re|dk)' -e '^gcj-(.*)-j(re|dk)' -e '^java-common' | xargs sudo apt$
- name: unistall java
  command: apt-get -y autoremove
- name: unistall java
  shell: dpkg -l | grep ^rc | awk '{print($2)}' | xargs sudo apt-get -y purge
- name: Remove Java config and cache directory
  shell: sudo bash -c 'ls -d /home/*/.java' | xargs sudo rm -rf

 #tasks file for java
- name: Download java
  get_url:
    url: https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.11/sapmachine-jdk-11.0.11_linux-x64_bin.tar.gz
    dest: /usr/java/


- name: unzip java
  unarchive:
    src:  /usr/java/sapmachine-jdk-11.0.11_linux-x64_bin.tar.gz
    dest: /usr/java/

- name: Move java
  command: mv /usr/java/sapmachine-jdk-11.0.11 /usr/java/latest

- name: export_java home
  shell: export JAVA_HOME=/usr/java/latest

- name: java path
  shell: export PATH=$PATH:$JAVA_HOME/bin





